version: "2.0"
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:5.4.3
    network_mode: host
    ports:
    - 2181:2181
    environment:
      ZOOKEEPER_CLIENT_PORT: "2181"
  kafka:
    image: confluentinc/cp-kafka:5.4.3
    network_mode: host
    ports:
    - 19092:19092
    environment:
      KAFKA_ZOOKEEPER_CONNECT: "localhost:2181"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://localhost:19092"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
    - zookeeper
  kafka-connect:
    image: confluentinc/cp-kafka-connect:5.4.3
    network_mode: host
    ports:
    - 8082:8082
    environment:
      CONNECT_BOOTSTRAP_SERVERS: localhost:19092
      CONNECT_REST_PORT: 8082
      CONNECT_GROUP_ID: "quickstart"
      CONNECT_CONFIG_STORAGE_TOPIC: "quickstart-config"
      CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: "1"
      CONNECT_OFFSET_STORAGE_TOPIC: "quickstart-offsets"
      CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: "1"
      CONNECT_STATUS_STORAGE_TOPIC: "quickstart-status"
      CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: "1"
      CONNECT_KEY_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_VALUE_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_INTERNAL_KEY_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_INTERNAL_VALUE_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_REST_ADVERTISED_HOST_NAME: "localhost"
    depends_on:
    - kafka
    volumes:
    - ./data:/tmp
